### ISSUE TITLE
Naive strategy: handle complex variants

### ISSUE THREAD

**Issue by armish** [hammerlab/isovar#2]
The current simple solution (#1) handles only SNVs and ignores more complex cases when extracting the context of a variant. It should handle indels too.

Sample code from @iskandr:
```python
if pileup_read.is_refskip:
    continue
elif len(variant.ref) == 0 and pileup_read.indel != len(variant.alt):
    continue
elif len(variant.alt) == 0 and pileup_read.indel != -len(variant.ref):
    continue
```

**Comment by iskandr** [comment]
Indels now supported, though I'm worried about `pysam` changing the meaning of some `PileupRead` flags.
