### ISSUE TITLE
Drop scikit-bio to avoid pinning an old version

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/isovar#29]
See https://github.com/hammerlab/isovar/issues/27#issuecomment-226257194

**Comment by hammer** [comment]
Use in `translation.py`: https://github.com/hammerlab/isovar/blob/master/isovar/translation.py#L268
Use in `reference_context.py`: https://github.com/hammerlab/isovar/blob/master/isovar/reference_context.py#L100
