### ISSUE TITLE
Results of isovar-protein-sequences.py no longer printed to screen

### ISSUE THREAD

**Issue by iskandr** [hammerlab/isovar#51]
I think our conversion to logging made it so that the results of isovar no longer get displayed by default. If the results are getting logged, how do I set the log level from the commandline? Otherwise, maybe we should go back to good old `print`.

**Comment by hammer** [comment]
Have you read the [Logging HOWTO](https://docs.python.org/3/howto/logging.html)?

Here's a relevant excerpt:
```
If you want to set the logging level from a command-line option such as:

--log=INFO
```

**Comment by iskandr** [comment]
That looks perfect.

**Comment by iskandr** [comment]
@julia326 This is fixed, right?

**Comment by julia326** [comment]
It is.
