### ISSUE TITLE
Count mismatches after variant toward total

### ISSUE THREAD

**Issue by julia326** [hammerlab/isovar#73]
From @iskandr :
`VariantInReadingFrame` has a `number_mismatch_before_variant`, you can add a `number_mismatch_after_variant` and filter on that unless some flag like `—allow-alternate-splicing` is supplied

**Comment by ihodes** [comment]
`—allow-alternate-splicing` should disable alternate splicing detection entirely; for disqualifying reads with N reads after variant, a flag like `--max-mismatch-after-variant` makes more sense to me.
